<div class="language float-right font-weight-semibold">
	<div class="title"><?php echo $block->escapeHtml(__('English')); ?></div>
    <div class="content" style="display: none;">
	    <div class="language-options">
	        <ul>
	            <li><a href=""><?php echo $block->escapeHtml(__('Language')); ?></a></li>
	            <li><a href=""><?php echo $block->escapeHtml(__('Language')); ?></a></li>
	            <li><a href=""><?php echo $block->escapeHtml(__('Language')); ?></a></li>
	            <li><a href=""><?php echo $block->escapeHtml(__('Language')); ?></a></li>
	            <li><a href=""><?php echo $block->escapeHtml(__('Language')); ?></a></li>
	        </ul>
	    </div>
	</div>
</div>